import io
import logging
import zipfile
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

logger = logging.getLogger(__name__)

TEMPLATES_DIR = Path(__file__).parent.parent / "templates"

# Type mapping filters
def python_type(openapi_type: str) -> str:
    return {
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "array": "list",
        "object": "dict",
    }.get(openapi_type, "str")


def ts_type(openapi_type: str) -> str:
    return {
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "array": "unknown[]",
        "object": "Record<string, unknown>",
    }.get(openapi_type, "string")


def _get_jinja_env() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape([]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["python_type"] = python_type
    env.filters["ts_type"] = ts_type
    return env


def generate_sdk(schema: dict, language: str) -> bytes:
    """
    Generate an SDK zip file from an API schema dict.
    Returns the zip file as bytes.
    """
    env = _get_jinja_env()
    api_name = schema.get("api_name", "MyAPI")
    class_name = api_name.replace(" ", "").replace("-", "")
    version = schema.get("version", "1.0.0")
    base_url = schema.get("base_url", "")
    auth = schema.get("auth_scheme") or {"type": "none", "header_name": "", "description": ""}
    endpoints = schema.get("endpoints", [])

    context = {
        "api_name": api_name,
        "class_name": class_name,
        "version": version,
        "base_url": base_url,
        "auth": auth,
        "endpoints": endpoints,
    }

    zip_buffer = io.BytesIO()

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        if language == "python":
            template = env.get_template("python_client.py.j2")
            code = template.render(**context)
            zf.writestr(f"{class_name.lower()}_client.py", code)
            zf.writestr("requirements.txt", "httpx>=0.27.0\n")
            zf.writestr("README.md", _generate_readme(api_name, language, endpoints))

        elif language == "typescript":
            template = env.get_template("typescript_client.ts.j2")
            code = template.render(**context)
            zf.writestr(f"{class_name.lower()}_client.ts", code)
            zf.writestr("package.json", _generate_package_json(class_name.lower()))
            zf.writestr("README.md", _generate_readme(api_name, language, endpoints))

    zip_buffer.seek(0)
    logger.info(f"Generated {language} SDK for {api_name} with {len(endpoints)} endpoints")
    return zip_buffer.read()


def _generate_readme(api_name: str, language: str, endpoints: list) -> str:
    endpoint_list = "\n".join(
        [f"- `{ep['method']} {ep['path']}` — {ep.get('summary', '')}" for ep in endpoints]
    )
    return f"""# {api_name} SDK

Auto-generated by [Smart DevTool](https://github.com/your-repo/smart-devtool).

## Endpoints

{endpoint_list}

## Usage

{"```python" if language == "python" else "```typescript"}
# Import and initialize the client
client = {api_name.replace(" ", "")}Client(base_url="...")
{"```" }

## Installation

{"pip install httpx" if language == "python" else "npm install"}
"""


def _generate_package_json(name: str) -> str:
    import json
    return json.dumps({
        "name": f"{name}-sdk",
        "version": "1.0.0",
        "description": f"Auto-generated SDK for {name}",
        "main": f"{name}_client.ts",
        "dependencies": {},
        "devDependencies": {"typescript": "^5.0.0"},
    }, indent=2)